/*
 * Algo Trading REST API
 *
 * Programmatic access to Binance’s execution algorithms for creating and managing Spot and Futures algo orders.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

pub mod future_algo_api;
pub use future_algo_api::*;
pub mod spot_algo_api;
pub use spot_algo_api::*;
