/*
 * Options WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade Binance Options.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalancePositionUpdatePInner {
    /// Symbol
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    /// Position quantity
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<String>,
    /// Position value
    #[serde(rename = "p", skip_serializing_if = "Option::is_none")]
    pub p: Option<String>,
    /// Average entry price
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<String>,
}

impl BalancePositionUpdatePInner {
    #[must_use]
    pub fn new() -> BalancePositionUpdatePInner {
        BalancePositionUpdatePInner {
            s: None,
            c: None,
            p: None,
            a: None,
        }
    }
}
