/*
 * Options REST API
 *
 * Access market data, manage accounts, and trade Binance Options.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoCancelAllOpenOrdersResponse {
    /// underlyings
    #[serde(rename = "underlyings", skip_serializing_if = "Option::is_none")]
    pub underlyings: Option<Vec<String>>,
}

impl AutoCancelAllOpenOrdersResponse {
    #[must_use]
    pub fn new() -> AutoCancelAllOpenOrdersResponse {
        AutoCancelAllOpenOrdersResponse { underlyings: None }
    }
}
