/*
 * Options REST API
 *
 * Access market data, manage accounts, and trade Binance Options.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_options::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBookResponse {
    /// Bid orders. Each entry is [price, quantity].
    #[serde(rename = "bids", skip_serializing_if = "Option::is_none")]
    pub bids: Option<Vec<Vec<String>>>,
    /// Ask orders. Each entry is [price, quantity].
    #[serde(rename = "asks", skip_serializing_if = "Option::is_none")]
    pub asks: Option<Vec<Vec<String>>>,
    /// transaction time
    #[serde(rename = "T", skip_serializing_if = "Option::is_none")]
    pub t_uppercase: Option<i64>,
    /// update id
    #[serde(rename = "lastUpdateId", skip_serializing_if = "Option::is_none")]
    pub last_update_id: Option<i64>,
}

impl OrderBookResponse {
    #[must_use]
    pub fn new() -> OrderBookResponse {
        OrderBookResponse {
            bids: None,
            asks: None,
            t_uppercase: None,
            last_update_id: None,
        }
    }
}
