/*
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

pub mod account_api;
pub use account_api::*;
pub mod borrow_repay_api;
pub use borrow_repay_api::*;
pub mod market_data_api;
pub use market_data_api::*;
pub mod trade_api;
pub use trade_api::*;
pub mod transfer_api;
pub use transfer_api::*;
pub mod user_data_stream_api;
pub use user_data_stream_api::*;
