/*
 * Stocks Trading WebSocket Streams
 *
 * WebSocket stream definitions for Binance Stocks Trading. Base URL: wss://nbstream.binance.com/equity
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::stocks::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarStreamResponse {
    /// Event type, always `\"calendar\"`.
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// Previous market phase.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// New market phase.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    /// Event timestamp (epoch milliseconds UTC) when the transition was detected.
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<i64>,
}

impl CalendarStreamResponse {
    #[must_use]
    pub fn new() -> CalendarStreamResponse {
        CalendarStreamResponse {
            e: None,
            from: None,
            to: None,
            ts: None,
        }
    }
}
