/*
 * Stocks Trading WebSocket Streams
 *
 * WebSocket stream definitions for Binance Stocks Trading. Base URL: wss://nbstream.binance.com/equity
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::stocks::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteStreamResponse {
    /// Event type, always `\"quote\"`.
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// Event time — epoch milliseconds when the server pushed the message.
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// Symbol (UPPERCASE ticker), e.g. `\"AAPL\"`.
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    /// Best bid price.
    #[serde(rename = "bp", skip_serializing_if = "Option::is_none")]
    pub bp: Option<String>,
    /// Best ask price.
    #[serde(rename = "ap", skip_serializing_if = "Option::is_none")]
    pub ap: Option<String>,
    /// Best bid size (shares).
    #[serde(rename = "bs", skip_serializing_if = "Option::is_none")]
    pub bs: Option<i32>,
    /// Best ask size (shares).
    #[serde(rename = "as", skip_serializing_if = "Option::is_none")]
    pub r#as: Option<i32>,
    /// Source quote timestamp (epoch milliseconds); may be null.
    #[serde(
        rename = "T",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub t_uppercase: Option<Option<i64>>,
}

impl QuoteStreamResponse {
    #[must_use]
    pub fn new() -> QuoteStreamResponse {
        QuoteStreamResponse {
            e: None,
            e_uppercase: None,
            s: None,
            bp: None,
            ap: None,
            bs: None,
            r#as: None,
            t_uppercase: None,
        }
    }
}
