/*
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::spot::websocket_api::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeInfoResponse {
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(rename = "serverTime", skip_serializing_if = "Option::is_none")]
    pub server_time: Option<i64>,
    #[serde(rename = "rateLimits", skip_serializing_if = "Option::is_none")]
    pub rate_limits: Option<Vec<models::RateLimits>>,
    #[serde(rename = "exchangeFilters", skip_serializing_if = "Option::is_none")]
    pub exchange_filters: Option<Vec<models::ExchangeFilters>>,
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<Vec<models::ExchangeInfoResponseSymbolsInner>>,
    #[serde(rename = "sors", skip_serializing_if = "Option::is_none")]
    pub sors: Option<Vec<models::ExchangeInfoResponseSorsInner>>,
}

impl ExchangeInfoResponse {
    #[must_use]
    pub fn new() -> ExchangeInfoResponse {
        ExchangeInfoResponse {
            timezone: None,
            server_time: None,
            rate_limits: None,
            exchange_filters: None,
            symbols: None,
            sors: None,
        }
    }
}
