/*
 * Spot WebSocket API
 *
 * Access market data, manage accounts, and trade on Binance Spot.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::spot::websocket_api::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutboundAccountPositionBInner {
    /// Asset
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<String>,
    /// Free
    #[serde(rename = "f", skip_serializing_if = "Option::is_none")]
    pub f: Option<String>,
    /// Locked
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<String>,
}

impl OutboundAccountPositionBInner {
    #[must_use]
    pub fn new() -> OutboundAccountPositionBInner {
        OutboundAccountPositionBInner {
            a: None,
            f: None,
            l: None,
        }
    }
}
