/*
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_usds_futures::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssetIndexResponse {
    AssetIndexResponse1(Box<models::AssetIndexResponse1>),
    AssetIndexResponse2(Vec<models::AssetIndexResponse2Inner>),
    Other(serde_json::Value),
}

impl Default for AssetIndexResponse {
    fn default() -> Self {
        Self::AssetIndexResponse1(Default::default())
    }
}
