/*
 * Futures (USDⓈ-M) REST API
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_usds_futures::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompressedAggregateTradesListResponseInner {
    /// Aggregate tradeId
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<i64>,
    /// Price
    #[serde(rename = "p", skip_serializing_if = "Option::is_none")]
    pub p: Option<String>,
    /// Quantity
    #[serde(rename = "q", skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Normal quantity without the trades involving RPI orders
    #[serde(rename = "nq", skip_serializing_if = "Option::is_none")]
    pub nq: Option<String>,
    /// First tradeId
    #[serde(rename = "f", skip_serializing_if = "Option::is_none")]
    pub f: Option<i64>,
    /// Last tradeId
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<i64>,
    /// Timestamp
    #[serde(rename = "T", skip_serializing_if = "Option::is_none")]
    pub t_uppercase: Option<i64>,
    /// Was the buyer the maker?
    #[serde(rename = "m", skip_serializing_if = "Option::is_none")]
    pub m: Option<bool>,
}

impl CompressedAggregateTradesListResponseInner {
    #[must_use]
    pub fn new() -> CompressedAggregateTradesListResponseInner {
        CompressedAggregateTradesListResponseInner {
            a: None,
            p: None,
            q: None,
            nq: None,
            f: None,
            l: None,
            t_uppercase: None,
            m: None,
        }
    }
}
