/*
 * Futures (COIN-M) REST API
 *
 * Access market data, manage accounts, and trade COIN-M perpetual and delivery futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_coin_futures::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartUserDataStreamResponse {
    /// Listen key.
    #[serde(rename = "listenKey", skip_serializing_if = "Option::is_none")]
    pub listen_key: Option<String>,
}

impl StartUserDataStreamResponse {
    #[must_use]
    pub fn new() -> StartUserDataStreamResponse {
        StartUserDataStreamResponse { listen_key: None }
    }
}
