/*
 * Futures (COIN-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade COIN-M perpetual and delivery futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_coin_futures::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractInfoStreamResponse {
    /// Event Type
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// Event Time
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// Symbol
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    /// Pair
    #[serde(rename = "ps", skip_serializing_if = "Option::is_none")]
    pub ps: Option<String>,
    /// Contract type
    #[serde(rename = "ct", skip_serializing_if = "Option::is_none")]
    pub ct: Option<String>,
    /// Delivery date time
    #[serde(rename = "dt", skip_serializing_if = "Option::is_none")]
    pub dt: Option<i64>,
    /// onboard date time
    #[serde(rename = "ot", skip_serializing_if = "Option::is_none")]
    pub ot: Option<i64>,
    /// Contract status
    #[serde(rename = "cs", skip_serializing_if = "Option::is_none")]
    pub cs: Option<String>,
    /// Bracket list.
    #[serde(rename = "bks", skip_serializing_if = "Option::is_none")]
    pub bks: Option<Vec<models::ContractInfoStreamResponseBksInner>>,
    /// (After CM migration) Symbol type: 1 = UM, 2 = CM
    #[serde(rename = "st", skip_serializing_if = "Option::is_none")]
    pub st: Option<i32>,
}

impl ContractInfoStreamResponse {
    #[must_use]
    pub fn new() -> ContractInfoStreamResponse {
        ContractInfoStreamResponse {
            e: None,
            e_uppercase: None,
            s: None,
            ps: None,
            ct: None,
            dt: None,
            ot: None,
            cs: None,
            bks: None,
            st: None,
        }
    }
}
