/*
 * Futures (COIN-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade COIN-M perpetual and delivery futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_coin_futures::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexPriceStreamResponse {
    /// Event type
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// Event time
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// Pair
    #[serde(rename = "i", skip_serializing_if = "Option::is_none")]
    pub i: Option<String>,
    /// Index Price
    #[serde(rename = "p", skip_serializing_if = "Option::is_none")]
    pub p: Option<String>,
}

impl IndexPriceStreamResponse {
    #[must_use]
    pub fn new() -> IndexPriceStreamResponse {
        IndexPriceStreamResponse {
            e: None,
            e_uppercase: None,
            i: None,
            p: None,
        }
    }
}
