/*
 * VIP Loan REST API
 *
 * Access over-collateralized loan services, manage positions, and monitor collateral via the VIP Loan API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

pub mod check_vip_loan_collateral_account_response;
pub use self::check_vip_loan_collateral_account_response::CheckVipLoanCollateralAccountResponse;
pub mod check_vip_loan_collateral_account_response_rows_inner;
pub use self::check_vip_loan_collateral_account_response_rows_inner::CheckVipLoanCollateralAccountResponseRowsInner;
pub mod get_borrow_interest_rate_response_inner;
pub use self::get_borrow_interest_rate_response_inner::GetBorrowInterestRateResponseInner;
pub mod get_collateral_asset_data_response;
pub use self::get_collateral_asset_data_response::GetCollateralAssetDataResponse;
pub mod get_collateral_asset_data_response_rows_inner;
pub use self::get_collateral_asset_data_response_rows_inner::GetCollateralAssetDataResponseRowsInner;
pub mod get_loanable_assets_data_response;
pub use self::get_loanable_assets_data_response::GetLoanableAssetsDataResponse;
pub mod get_loanable_assets_data_response_rows_inner;
pub use self::get_loanable_assets_data_response_rows_inner::GetLoanableAssetsDataResponseRowsInner;
pub mod get_vip_loan_accrued_interest_response;
pub use self::get_vip_loan_accrued_interest_response::GetVipLoanAccruedInterestResponse;
pub mod get_vip_loan_accrued_interest_response_rows_inner;
pub use self::get_vip_loan_accrued_interest_response_rows_inner::GetVipLoanAccruedInterestResponseRowsInner;
pub mod get_vip_loan_interest_rate_history_response;
pub use self::get_vip_loan_interest_rate_history_response::GetVipLoanInterestRateHistoryResponse;
pub mod get_vip_loan_interest_rate_history_response_rows_inner;
pub use self::get_vip_loan_interest_rate_history_response_rows_inner::GetVipLoanInterestRateHistoryResponseRowsInner;
pub mod get_vip_loan_ongoing_orders_response;
pub use self::get_vip_loan_ongoing_orders_response::GetVipLoanOngoingOrdersResponse;
pub mod get_vip_loan_ongoing_orders_response_rows_inner;
pub use self::get_vip_loan_ongoing_orders_response_rows_inner::GetVipLoanOngoingOrdersResponseRowsInner;
pub mod get_vip_loan_repayment_history_response;
pub use self::get_vip_loan_repayment_history_response::GetVipLoanRepaymentHistoryResponse;
pub mod get_vip_loan_repayment_history_response_rows_inner;
pub use self::get_vip_loan_repayment_history_response_rows_inner::GetVipLoanRepaymentHistoryResponseRowsInner;
pub mod query_application_status_response;
pub use self::query_application_status_response::QueryApplicationStatusResponse;
pub mod query_application_status_response_rows_inner;
pub use self::query_application_status_response_rows_inner::QueryApplicationStatusResponseRowsInner;
pub mod query_vip_loan_fixed_rate_market_response;
pub use self::query_vip_loan_fixed_rate_market_response::QueryVipLoanFixedRateMarketResponse;
pub mod query_vip_loan_fixed_rate_market_response_rows_inner;
pub use self::query_vip_loan_fixed_rate_market_response_rows_inner::QueryVipLoanFixedRateMarketResponseRowsInner;
pub mod vip_loan_borrow_response;
pub use self::vip_loan_borrow_response::VipLoanBorrowResponse;
pub mod vip_loan_fixed_rate_borrow_response;
pub use self::vip_loan_fixed_rate_borrow_response::VipLoanFixedRateBorrowResponse;
pub mod vip_loan_renew_response;
pub use self::vip_loan_renew_response::VipLoanRenewResponse;
pub mod vip_loan_repay_response;
pub use self::vip_loan_repay_response::VipLoanRepayResponse;
