/*
 * Mining REST API
 *
 * Query mining status, earnings, and account data via the Binance Pool API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::mining::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashrateResaleDetailResponseData {
    #[serde(
        rename = "profitTransferDetails",
        skip_serializing_if = "Option::is_none"
    )]
    pub profit_transfer_details:
        Option<Vec<models::HashrateResaleDetailResponseDataProfitTransferDetailsInner>>,
    /// Total rows
    #[serde(rename = "totalNum", skip_serializing_if = "Option::is_none")]
    pub total_num: Option<i64>,
    /// Rows per page
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
}

impl HashrateResaleDetailResponseData {
    #[must_use]
    pub fn new() -> HashrateResaleDetailResponseData {
        HashrateResaleDetailResponseData {
            profit_transfer_details: None,
            total_num: None,
            page_size: None,
        }
    }
}
