/*
 * Staking REST API
 *
 * Subscribe to staking products, track positions, and query rewards via the Binance Staking API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use http::Method;
use serde::de::DeserializeOwned;
use serde_json::Value;
use std::collections::BTreeMap;

use crate::common::{config::ConfigurationRestApi, models::RestApiResponse, utils::send_request};

mod apis;
mod models;

pub use apis::*;
pub use models::*;

#[derive(Debug, Clone)]
pub struct RestApi {
    configuration: ConfigurationRestApi,
    eth_staking_api_client: EthStakingApiClient,
    on_chain_yields_api_client: OnChainYieldsApiClient,
    soft_staking_api_client: SoftStakingApiClient,
    sol_staking_api_client: SolStakingApiClient,
}

impl RestApi {
    pub fn new(configuration: ConfigurationRestApi) -> Self {
        let eth_staking_api_client = EthStakingApiClient::new(configuration.clone());
        let on_chain_yields_api_client = OnChainYieldsApiClient::new(configuration.clone());
        let soft_staking_api_client = SoftStakingApiClient::new(configuration.clone());
        let sol_staking_api_client = SolStakingApiClient::new(configuration.clone());

        Self {
            configuration,
            eth_staking_api_client,
            on_chain_yields_api_client,
            soft_staking_api_client,
            sol_staking_api_client,
        }
    }

    /// Send an unsigned request to the API
    ///
    /// # Arguments
    ///
    /// * `endpoint` - The API endpoint to send the request to
    /// * `method` - The HTTP method to use for the request
    /// * `query_params` - A map of query parameters to send with the request
    /// * `body_params` - A map of body parameters to send with the request
    ///
    /// # Returns
    ///
    /// A `RestApiResponse` containing the deserialized response data on success, or an error if the request fails
    ///
    /// # Errors
    ///
    /// Returns an `anyhow::Error` if the HTTP request fails or if parsing the response fails
    pub async fn send_request<R: DeserializeOwned + Send + 'static>(
        &self,
        endpoint: &str,
        method: Method,
        query_params: BTreeMap<String, Value>,
        body_params: BTreeMap<String, Value>,
    ) -> anyhow::Result<RestApiResponse<R>> {
        send_request::<R>(
            &self.configuration,
            endpoint,
            method,
            query_params,
            body_params,
            None,
            false,
        )
        .await
    }

    /// Send a signed request to the API
    ///
    /// # Arguments
    ///
    /// * `endpoint` - The API endpoint to send the request to
    /// * `method` - The HTTP method to use for the request
    /// * `query_params` - A map of query parameters to send with the request
    /// * `body_params` - A map of body parameters to send with the request
    ///
    /// # Returns
    ///
    /// A `RestApiResponse` containing the deserialized response data on success, or an error if the request fails
    ///
    /// # Errors
    ///
    /// Returns an `anyhow::Error` if the HTTP request fails or if parsing the response fails
    pub async fn send_signed_request<R: DeserializeOwned + Send + 'static>(
        &self,
        endpoint: &str,
        method: Method,
        query_params: BTreeMap<String, Value>,
        body_params: BTreeMap<String, Value>,
    ) -> anyhow::Result<RestApiResponse<R>> {
        send_request::<R>(
            &self.configuration,
            endpoint,
            method,
            query_params,
            body_params,
            None,
            true,
        )
        .await
    }

    /// ETH Staking account (`USER_DATA`)
    ///
    /// ETH Staking account
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`EthStakingAccountParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::EthStakingAccountResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#eth-staking-account).
    ///
    pub async fn eth_staking_account(
        &self,
        params: EthStakingAccountParams,
    ) -> anyhow::Result<RestApiResponse<models::EthStakingAccountResponse>> {
        self.eth_staking_api_client
            .eth_staking_account(params)
            .await
    }

    /// Get current ETH staking quota (`USER_DATA`)
    ///
    /// Get current ETH staking quota
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetCurrentEthStakingQuotaParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetCurrentEthStakingQuotaResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-current-eth-staking-quota).
    ///
    pub async fn get_current_eth_staking_quota(
        &self,
        params: GetCurrentEthStakingQuotaParams,
    ) -> anyhow::Result<RestApiResponse<models::GetCurrentEthStakingQuotaResponse>> {
        self.eth_staking_api_client
            .get_current_eth_staking_quota(params)
            .await
    }

    /// Get ETH redemption history (`USER_DATA`)
    ///
    /// Get ETH redemption history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetEthRedemptionHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetEthRedemptionHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-eth-redemption-history).
    ///
    pub async fn get_eth_redemption_history(
        &self,
        params: GetEthRedemptionHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetEthRedemptionHistoryResponse>> {
        self.eth_staking_api_client
            .get_eth_redemption_history(params)
            .await
    }

    /// Get ETH staking history (`USER_DATA`)
    ///
    /// Get ETH staking history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetEthStakingHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetEthStakingHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-eth-staking-history).
    ///
    pub async fn get_eth_staking_history(
        &self,
        params: GetEthStakingHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetEthStakingHistoryResponse>> {
        self.eth_staking_api_client
            .get_eth_staking_history(params)
            .await
    }

    /// Get WBETH Rate History (`USER_DATA`)
    ///
    /// Get WBETH Rate History
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetWbethRateHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetWbethRateHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-wbeth-rate-history).
    ///
    pub async fn get_wbeth_rate_history(
        &self,
        params: GetWbethRateHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetWbethRateHistoryResponse>> {
        self.eth_staking_api_client
            .get_wbeth_rate_history(params)
            .await
    }

    /// Get WBETH rewards history (`USER_DATA`)
    ///
    /// Get WBETH rewards history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetWbethRewardsHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetWbethRewardsHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-wbeth-rewards-history).
    ///
    pub async fn get_wbeth_rewards_history(
        &self,
        params: GetWbethRewardsHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetWbethRewardsHistoryResponse>> {
        self.eth_staking_api_client
            .get_wbeth_rewards_history(params)
            .await
    }

    /// Get WBETH unwrap history (`USER_DATA`)
    ///
    /// Get WBETH unwrap history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetWbethUnwrapHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetWbethUnwrapHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-wbeth-unwrap-history).
    ///
    pub async fn get_wbeth_unwrap_history(
        &self,
        params: GetWbethUnwrapHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetWbethUnwrapHistoryResponse>> {
        self.eth_staking_api_client
            .get_wbeth_unwrap_history(params)
            .await
    }

    /// Get WBETH wrap history (`USER_DATA`)
    ///
    /// Get WBETH wrap history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetWbethWrapHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetWbethWrapHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#get-wbeth-wrap-history).
    ///
    pub async fn get_wbeth_wrap_history(
        &self,
        params: GetWbethWrapHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetWbethWrapHistoryResponse>> {
        self.eth_staking_api_client
            .get_wbeth_wrap_history(params)
            .await
    }

    /// Redeem ETH (TRADE)
    ///
    /// Redeem WBETH or BETH and get ETH
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open Enable Spot & Margin Trading permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`RedeemEthParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::RedeemEthResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#redeem-eth).
    ///
    pub async fn redeem_eth(
        &self,
        params: RedeemEthParams,
    ) -> anyhow::Result<RestApiResponse<models::RedeemEthResponse>> {
        self.eth_staking_api_client.redeem_eth(params).await
    }

    /// Subscribe ETH Staking (TRADE)
    ///
    /// Subscribe ETH Staking
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open Enable Spot & Margin Trading permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`SubscribeEthStakingParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SubscribeEthStakingResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#subscribe-eth-staking).
    ///
    pub async fn subscribe_eth_staking(
        &self,
        params: SubscribeEthStakingParams,
    ) -> anyhow::Result<RestApiResponse<models::SubscribeEthStakingResponse>> {
        self.eth_staking_api_client
            .subscribe_eth_staking(params)
            .await
    }

    /// Wrap BETH (TRADE)
    ///
    /// Wrap BETH
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open Enable Spot & Margin Trading permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`WrapBethParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::WrapBethResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/eth-staking#wrap-beth).
    ///
    pub async fn wrap_beth(
        &self,
        params: WrapBethParams,
    ) -> anyhow::Result<RestApiResponse<models::WrapBethResponse>> {
        self.eth_staking_api_client.wrap_beth(params).await
    }

    /// Get On-chain Yields Locked Personal Left Quota (`USER_DATA`)
    ///
    /// Get On-chain Yields Locked Personal Left Quota
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedPersonalLeftQuotaParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedPersonalLeftQuotaResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-personal-left-quota).
    ///
    pub async fn get_on_chain_yields_locked_personal_left_quota(
        &self,
        params: GetOnChainYieldsLockedPersonalLeftQuotaParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedPersonalLeftQuotaResponse>>
    {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_personal_left_quota(params)
            .await
    }

    /// Get On-chain Yields Locked Product List (`USER_DATA`)
    ///
    /// Get available On-chain Yields Locked product list
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - Get available On-chain Yields Locked product list
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedProductListParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedProductListResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-product-list).
    ///
    pub async fn get_on_chain_yields_locked_product_list(
        &self,
        params: GetOnChainYieldsLockedProductListParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedProductListResponse>> {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_product_list(params)
            .await
    }

    /// Get On-chain Yields Locked Product Position (`USER_DATA`)
    ///
    /// Get On-chain Yields Locked Product Position
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedProductPositionParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedProductPositionResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-product-position).
    ///
    pub async fn get_on_chain_yields_locked_product_position(
        &self,
        params: GetOnChainYieldsLockedProductPositionParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedProductPositionResponse>>
    {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_product_position(params)
            .await
    }

    /// Get On-chain Yields Locked Redemption Record (`USER_DATA`)
    ///
    /// Get On-chain Yields Locked Redemption Record
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedRedemptionRecordParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedRedemptionRecordResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-redemption-record).
    ///
    pub async fn get_on_chain_yields_locked_redemption_record(
        &self,
        params: GetOnChainYieldsLockedRedemptionRecordParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedRedemptionRecordResponse>>
    {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_redemption_record(params)
            .await
    }

    /// Get On-chain Yields Locked Rewards History (`USER_DATA`)
    ///
    /// Get On-chain Yields Locked Rewards History
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedRewardsHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedRewardsHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-rewards-history).
    ///
    pub async fn get_on_chain_yields_locked_rewards_history(
        &self,
        params: GetOnChainYieldsLockedRewardsHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedRewardsHistoryResponse>> {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_rewards_history(params)
            .await
    }

    /// Get On-chain Yields Locked Subscription Preview (`USER_DATA`)
    ///
    /// Get On-chain Yields Locked Subscription Preview
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedSubscriptionPreviewParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedSubscriptionPreviewResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-subscription-preview).
    ///
    pub async fn get_on_chain_yields_locked_subscription_preview(
        &self,
        params: GetOnChainYieldsLockedSubscriptionPreviewParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedSubscriptionPreviewResponse>>
    {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_subscription_preview(params)
            .await
    }

    /// Get On-chain Yields Locked Subscription Record (`USER_DATA`)
    ///
    /// Get On-chain Yields Locked Subscription Record
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetOnChainYieldsLockedSubscriptionRecordParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetOnChainYieldsLockedSubscriptionRecordResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-subscription-record).
    ///
    pub async fn get_on_chain_yields_locked_subscription_record(
        &self,
        params: GetOnChainYieldsLockedSubscriptionRecordParams,
    ) -> anyhow::Result<RestApiResponse<models::GetOnChainYieldsLockedSubscriptionRecordResponse>>
    {
        self.on_chain_yields_api_client
            .get_on_chain_yields_locked_subscription_record(params)
            .await
    }

    /// On-chain Yields Account (`USER_DATA`)
    ///
    /// On-chain Yields Account query
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`OnChainYieldsAccountParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::OnChainYieldsAccountResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#on-chain-yields-account).
    ///
    pub async fn on_chain_yields_account(
        &self,
        params: OnChainYieldsAccountParams,
    ) -> anyhow::Result<RestApiResponse<models::OnChainYieldsAccountResponse>> {
        self.on_chain_yields_api_client
            .on_chain_yields_account(params)
            .await
    }

    /// Redeem On-chain Yields Locked Product (TRADE)
    ///
    /// Redeem On-chain Yields Locked Product
    ///
    /// Weight(IP): 200
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`RedeemOnChainYieldsLockedProductParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::RedeemOnChainYieldsLockedProductResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#redeem-on-chain-yields-locked-product).
    ///
    pub async fn redeem_on_chain_yields_locked_product(
        &self,
        params: RedeemOnChainYieldsLockedProductParams,
    ) -> anyhow::Result<RestApiResponse<models::RedeemOnChainYieldsLockedProductResponse>> {
        self.on_chain_yields_api_client
            .redeem_on_chain_yields_locked_product(params)
            .await
    }

    /// Set On-chain Yields Locked Auto Subscribe (`USER_DATA`)
    ///
    /// Set On-chain Yield locked auto subscribe
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`SetOnChainYieldsLockedAutoSubscribeParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SetOnChainYieldsLockedAutoSubscribeResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#set-on-chain-yields-locked-auto-subscribe).
    ///
    pub async fn set_on_chain_yields_locked_auto_subscribe(
        &self,
        params: SetOnChainYieldsLockedAutoSubscribeParams,
    ) -> anyhow::Result<RestApiResponse<models::SetOnChainYieldsLockedAutoSubscribeResponse>> {
        self.on_chain_yields_api_client
            .set_on_chain_yields_locked_auto_subscribe(params)
            .await
    }

    /// Set On-chain Yields Locked Product Redeem Option (`USER_DATA`)
    ///
    /// Set On-chain Yields redeem option for Locked product
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`SetOnChainYieldsLockedProductRedeemOptionParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SetOnChainYieldsLockedProductRedeemOptionResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#set-on-chain-yields-locked-product-redeem-option).
    ///
    pub async fn set_on_chain_yields_locked_product_redeem_option(
        &self,
        params: SetOnChainYieldsLockedProductRedeemOptionParams,
    ) -> anyhow::Result<RestApiResponse<models::SetOnChainYieldsLockedProductRedeemOptionResponse>>
    {
        self.on_chain_yields_api_client
            .set_on_chain_yields_locked_product_redeem_option(params)
            .await
    }

    /// Subscribe On-chain Yields Locked Product (TRADE)
    ///
    /// Subscribe On-chain Yields Locked Product
    ///
    /// Weight(IP): 200
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`SubscribeOnChainYieldsLockedProductParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SubscribeOnChainYieldsLockedProductResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#subscribe-on-chain-yields-locked-product).
    ///
    pub async fn subscribe_on_chain_yields_locked_product(
        &self,
        params: SubscribeOnChainYieldsLockedProductParams,
    ) -> anyhow::Result<RestApiResponse<models::SubscribeOnChainYieldsLockedProductResponse>> {
        self.on_chain_yields_api_client
            .subscribe_on_chain_yields_locked_product(params)
            .await
    }

    /// Get Soft Staking Product List (`USER_DATA`)
    ///
    /// Get the available Soft Staking product list.
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetSoftStakingProductListParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetSoftStakingProductListResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/soft-staking#get-soft-staking-product-list).
    ///
    pub async fn get_soft_staking_product_list(
        &self,
        params: GetSoftStakingProductListParams,
    ) -> anyhow::Result<RestApiResponse<models::GetSoftStakingProductListResponse>> {
        self.soft_staking_api_client
            .get_soft_staking_product_list(params)
            .await
    }

    /// Get Soft Staking Rewards History (`USER_DATA`)
    ///
    /// Get Soft Staking Rewards History
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetSoftStakingRewardsHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetSoftStakingRewardsHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/soft-staking#get-soft-staking-rewards-history).
    ///
    pub async fn get_soft_staking_rewards_history(
        &self,
        params: GetSoftStakingRewardsHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetSoftStakingRewardsHistoryResponse>> {
        self.soft_staking_api_client
            .get_soft_staking_rewards_history(params)
            .await
    }

    /// Set Soft Staking (`USER_DATA`)
    ///
    /// Enable or disable Soft Staking.
    ///
    /// Weight(IP): 50
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`SetSoftStakingParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SetSoftStakingResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/soft-staking#set-soft-staking).
    ///
    pub async fn set_soft_staking(
        &self,
        params: SetSoftStakingParams,
    ) -> anyhow::Result<RestApiResponse<models::SetSoftStakingResponse>> {
        self.soft_staking_api_client.set_soft_staking(params).await
    }

    /// Claim Boost Rewards (TRADE)
    ///
    /// Claim Boost APR Airdrop Rewards
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open Enable Spot & Margin Trading permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`ClaimBoostRewardsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::ClaimBoostRewardsResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#claim-boost-rewards).
    ///
    pub async fn claim_boost_rewards(
        &self,
        params: ClaimBoostRewardsParams,
    ) -> anyhow::Result<RestApiResponse<models::ClaimBoostRewardsResponse>> {
        self.sol_staking_api_client
            .claim_boost_rewards(params)
            .await
    }

    /// Get BNSOL Rate History (`USER_DATA`)
    ///
    /// Get BNSOL Rate History
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetBnsolRateHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetBnsolRateHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-bnsol-rate-history).
    ///
    pub async fn get_bnsol_rate_history(
        &self,
        params: GetBnsolRateHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetBnsolRateHistoryResponse>> {
        self.sol_staking_api_client
            .get_bnsol_rate_history(params)
            .await
    }

    /// Get BNSOL rewards history (`USER_DATA`)
    ///
    /// Get BNSOL rewards history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetBnsolRewardsHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetBnsolRewardsHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-bnsol-rewards-history).
    ///
    pub async fn get_bnsol_rewards_history(
        &self,
        params: GetBnsolRewardsHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetBnsolRewardsHistoryResponse>> {
        self.sol_staking_api_client
            .get_bnsol_rewards_history(params)
            .await
    }

    /// Get Boost Rewards History (`USER_DATA`)
    ///
    /// Get Boost rewards history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetBoostRewardsHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetBoostRewardsHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-boost-rewards-history).
    ///
    pub async fn get_boost_rewards_history(
        &self,
        params: GetBoostRewardsHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetBoostRewardsHistoryResponse>> {
        self.sol_staking_api_client
            .get_boost_rewards_history(params)
            .await
    }

    /// Get SOL redemption history (`USER_DATA`)
    ///
    /// Get SOL redemption history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetSolRedemptionHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetSolRedemptionHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-sol-redemption-history).
    ///
    pub async fn get_sol_redemption_history(
        &self,
        params: GetSolRedemptionHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetSolRedemptionHistoryResponse>> {
        self.sol_staking_api_client
            .get_sol_redemption_history(params)
            .await
    }

    /// Get SOL staking history (`USER_DATA`)
    ///
    /// Get SOL staking history
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetSolStakingHistoryParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetSolStakingHistoryResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-sol-staking-history).
    ///
    pub async fn get_sol_staking_history(
        &self,
        params: GetSolStakingHistoryParams,
    ) -> anyhow::Result<RestApiResponse<models::GetSolStakingHistoryResponse>> {
        self.sol_staking_api_client
            .get_sol_staking_history(params)
            .await
    }

    /// Get SOL staking quota details (`USER_DATA`)
    ///
    /// Get SOL staking quota
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetSolStakingQuotaDetailsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::GetSolStakingQuotaDetailsResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-sol-staking-quota-details).
    ///
    pub async fn get_sol_staking_quota_details(
        &self,
        params: GetSolStakingQuotaDetailsParams,
    ) -> anyhow::Result<RestApiResponse<models::GetSolStakingQuotaDetailsResponse>> {
        self.sol_staking_api_client
            .get_sol_staking_quota_details(params)
            .await
    }

    /// Get Unclaimed Rewards (`USER_DATA`)
    ///
    /// Get Unclaimed rewards
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// Notes:
    /// - The time between `startTime` and `endTime` cannot be longer than 3 months.
    /// - If `startTime` and `endTime`
    /// are both not sent, then the last 30 days' data will be returned.
    /// - If `startTime` is sent but `endTime` is not
    /// sent, the next 30 days' data beginning from `startTime` will be returned.
    /// - If `endTime` is sent but
    /// `startTime` is not sent, the 30 days' data before `endTime` will be returned.
    ///
    /// # Arguments
    ///
    /// - `params`: [`GetUnclaimedRewardsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<Vec<models::GetUnclaimedRewardsResponseInner>>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#get-unclaimed-rewards).
    ///
    pub async fn get_unclaimed_rewards(
        &self,
        params: GetUnclaimedRewardsParams,
    ) -> anyhow::Result<RestApiResponse<Vec<models::GetUnclaimedRewardsResponseInner>>> {
        self.sol_staking_api_client
            .get_unclaimed_rewards(params)
            .await
    }

    /// Redeem SOL (TRADE)
    ///
    /// Redeem BNSOL get SOL
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open Enable Spot & Margin Trading permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`RedeemSolParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::RedeemSolResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#redeem-sol).
    ///
    pub async fn redeem_sol(
        &self,
        params: RedeemSolParams,
    ) -> anyhow::Result<RestApiResponse<models::RedeemSolResponse>> {
        self.sol_staking_api_client.redeem_sol(params).await
    }

    /// SOL Staking account (`USER_DATA`)
    ///
    /// SOL Staking account
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: `USER_DATA`
    ///
    /// # Arguments
    ///
    /// - `params`: [`SolStakingAccountParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SolStakingAccountResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#sol-staking-account).
    ///
    pub async fn sol_staking_account(
        &self,
        params: SolStakingAccountParams,
    ) -> anyhow::Result<RestApiResponse<models::SolStakingAccountResponse>> {
        self.sol_staking_api_client
            .sol_staking_account(params)
            .await
    }

    /// Subscribe SOL Staking (TRADE)
    ///
    /// Subscribe SOL Staking
    ///
    /// Weight(IP): 150
    ///
    /// Security Type: TRADE
    ///
    /// Notes:
    /// - You need to open Enable Spot & Margin Trading permission for the API Key which requests this endpoint.
    ///
    /// # Arguments
    ///
    /// - `params`: [`SubscribeSolStakingParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`RestApiResponse<models::SubscribeSolStakingResponse>`] on success.
    ///
    /// # Errors
    ///
    /// This function will return an [`anyhow::Error`] if:
    /// - the HTTP request fails
    /// - any parameter is invalid
    /// - the response cannot be parsed
    /// - or one of the following occurs:
    ///   - `RequiredError`
    ///   - `ConnectorClientError`
    ///   - `UnauthorizedError`
    ///   - `ForbiddenError`
    ///   - `TooManyRequestsError`
    ///   - `RateLimitBanError`
    ///   - `ServerError`
    ///   - `NotFoundError`
    ///   - `NetworkError`
    ///   - `BadRequestError`
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/investment-and-services-staking/api/rest-api/sol-staking#subscribe-sol-staking).
    ///
    pub async fn subscribe_sol_staking(
        &self,
        params: SubscribeSolStakingParams,
    ) -> anyhow::Result<RestApiResponse<models::SubscribeSolStakingResponse>> {
        self.sol_staking_api_client
            .subscribe_sol_staking(params)
            .await
    }
}
