/*
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::simple_earn::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetYieldArenaActivitiesResponse {
    #[serde(rename = "activities", skip_serializing_if = "Option::is_none")]
    pub activities: Option<Vec<models::GetYieldArenaActivitiesResponseActivitiesInner>>,
}

impl GetYieldArenaActivitiesResponse {
    #[must_use]
    pub fn new() -> GetYieldArenaActivitiesResponse {
        GetYieldArenaActivitiesResponse { activities: None }
    }
}
