/*
 * Copy Trading REST API
 *
 * Automate lead trading via the Copy Trading API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::copy_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFuturesLeadTraderStatusResponse {
    /// API response code. \"000000\" indicates success.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Response message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::GetFuturesLeadTraderStatusResponseData>>,
    /// Whether request is successful
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl GetFuturesLeadTraderStatusResponse {
    #[must_use]
    pub fn new() -> GetFuturesLeadTraderStatusResponse {
        GetFuturesLeadTraderStatusResponse {
            code: None,
            message: None,
            data: None,
            success: None,
        }
    }
}
