/*
 * Alpha WebSocket Market Streams
 *
 * Access Alpha market streams over WebSocket.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::alpha::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookTickerStreamResponse {
    /// eventType
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// eventTime
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// transactionTime
    #[serde(rename = "T", skip_serializing_if = "Option::is_none")]
    pub t_uppercase: Option<i64>,
    /// updateId
    #[serde(rename = "u", skip_serializing_if = "Option::is_none")]
    pub u: Option<i64>,
    /// symbol
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    /// bid1Price
    #[serde(rename = "b", skip_serializing_if = "Option::is_none")]
    pub b: Option<String>,
    /// bid1Quantity
    #[serde(rename = "B", skip_serializing_if = "Option::is_none")]
    pub b_uppercase: Option<String>,
    /// ask1Price
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<String>,
    /// ask1Quantity
    #[serde(rename = "A", skip_serializing_if = "Option::is_none")]
    pub a_uppercase: Option<String>,
}

impl BookTickerStreamResponse {
    #[must_use]
    pub fn new() -> BookTickerStreamResponse {
        BookTickerStreamResponse {
            e: None,
            e_uppercase: None,
            t_uppercase: None,
            u: None,
            s: None,
            b: None,
            b_uppercase: None,
            a: None,
            a_uppercase: None,
        }
    }
}
