/*
 * Alpha WebSocket Market Streams
 *
 * Access Alpha market streams over WebSocket.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::alpha::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KlineStreamResponse {
    /// eventType
    #[serde(rename = "e", skip_serializing_if = "Option::is_none")]
    pub e: Option<String>,
    /// eventTime
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// symbol
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    #[serde(rename = "k", skip_serializing_if = "Option::is_none")]
    pub k: Option<Box<models::KlineStreamResponseK>>,
}

impl KlineStreamResponse {
    #[must_use]
    pub fn new() -> KlineStreamResponse {
        KlineStreamResponse {
            e: None,
            e_uppercase: None,
            s: None,
            k: None,
        }
    }
}
