/*
 * Portfolio Margin WebSocket Market Streams
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_portfolio_margin::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountUpdate {
    /// Event business unit. 'UM' for USDS-M futures and 'CM' for COIN-M futures
    #[serde(rename = "fs", skip_serializing_if = "Option::is_none")]
    pub fs: Option<String>,
    /// Event Time
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// Transaction
    #[serde(rename = "T", skip_serializing_if = "Option::is_none")]
    pub t_uppercase: Option<i64>,
    /// Account Alias, ignore for UM
    #[serde(rename = "i", skip_serializing_if = "Option::is_none")]
    pub i: Option<String>,
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<Box<models::AccountUpdateA>>,
}

impl AccountUpdate {
    #[must_use]
    pub fn new() -> AccountUpdate {
        AccountUpdate {
            fs: None,
            e_uppercase: None,
            t_uppercase: None,
            i: None,
            a: None,
        }
    }
}
