/*
 * Portfolio Margin WebSocket Market Streams
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_portfolio_margin::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiabilityChange {
    /// Event Time
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e_uppercase: Option<i64>,
    /// Asset
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<String>,
    /// Type
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<String>,
    /// Transaction ID
    #[serde(rename = "T", skip_serializing_if = "Option::is_none")]
    pub t_uppercase: Option<i64>,
    /// Principal
    #[serde(rename = "p", skip_serializing_if = "Option::is_none")]
    pub p: Option<String>,
    /// Interest
    #[serde(rename = "i", skip_serializing_if = "Option::is_none")]
    pub i: Option<String>,
    /// Total Liability
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<String>,
}

impl LiabilityChange {
    #[must_use]
    pub fn new() -> LiabilityChange {
        LiabilityChange {
            e_uppercase: None,
            a: None,
            t: None,
            t_uppercase: None,
            p: None,
            i: None,
            l: None,
        }
    }
}
