/*
 * Portfolio Margin WebSocket Market Streams
 *
 * Access account information, manage margin positions, and trade with Binance Portfolio Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::derivatives_trading_portfolio_margin::websocket_streams::models;
use serde::{Deserialize, Deserializer, Serialize, de::Error};
use serde_json::Value;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenOrderLossOInner {
    /// Asset
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<String>,
    /// Amount
    #[serde(rename = "o", skip_serializing_if = "Option::is_none")]
    pub o: Option<String>,
}

impl OpenOrderLossOInner {
    #[must_use]
    pub fn new() -> OpenOrderLossOInner {
        OpenOrderLossOInner { a: None, o: None }
    }
}
