/*
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::margin_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLimitPricePairsResponse {
    /// cross Margin Symbols list.
    #[serde(rename = "crossMarginSymbols", skip_serializing_if = "Option::is_none")]
    pub cross_margin_symbols: Option<Vec<String>>,
}

impl GetLimitPricePairsResponse {
    #[must_use]
    pub fn new() -> GetLimitPricePairsResponse {
        GetLimitPricePairsResponse {
            cross_margin_symbols: None,
        }
    }
}
