/*
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::margin_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryMaxBorrowResponse {
    /// account's currently max borrowable amount with sufficient system availability
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// max borrowable amount limited by the account level
    #[serde(rename = "borrowLimit", skip_serializing_if = "Option::is_none")]
    pub borrow_limit: Option<String>,
}

impl QueryMaxBorrowResponse {
    #[must_use]
    pub fn new() -> QueryMaxBorrowResponse {
        QueryMaxBorrowResponse {
            amount: None,
            borrow_limit: None,
        }
    }
}
