/*
 * Margin REST API
 *
 * Access account information, borrow and repay assets, and trade with Binance Margin.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use crate::margin_trading::rest_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryMarginAvailableInventoryResponse {
    /// Available inventory per asset. Keys are asset symbols, values are available amounts.
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<std::collections::HashMap<String, String>>,
    /// update Time.
    #[serde(rename = "updateTime", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<i64>,
}

impl QueryMarginAvailableInventoryResponse {
    #[must_use]
    pub fn new() -> QueryMarginAvailableInventoryResponse {
        QueryMarginAvailableInventoryResponse {
            assets: None,
            update_time: None,
        }
    }
}
